import Link from 'next/link'
import './globals.css'
import Navigation from '@/components/Navigation'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Tim</title>
      </head>
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  )
}
